### ISSUE TITLE
텍스트 제목이 길 경우, .... 이 표시 안되고 있음.

### ISSUE THREAD

**Issue by biud436** [biud436/project_one#12]
![image](https://user-images.githubusercontent.com/13586185/98323412-0ede5100-202d-11eb-8262-350ece090d1f.png)

```css
.item-button-container {
    width: 100%;
    height: 5.5em;
    line-height: 2em;
    display: flex;
    font-size: 0.675em;
    text-align: center;
    flex-direction: column;
    overflow: hidden;
    text-overflow: ellipsis;
    text-emphasis-style: dot;
    white-space: nowrap;
    border: none;
}
```
