### ISSUE TITLE
CSS 리팩토링 필요

### ISSUE THREAD

**Issue by biud436** [biud436/project_one#14]
작업 중에 느낀 것인데 현재 불필요한 코드가 상당히 많습니다.

공통된 사이즈, 간격, 정렬 속성은 별도의 클래스로 만들어서 모듈화  하는 게 좋을 것 같습니다.

처음부터 잡고 갔어야 했으나 이미 늦었기 때문에 장기적인 목표로 잡았습니다.

# 간격
그리드 시스템처럼 화면을 1단계에서 16단계로 나눠야 할 것 같습니다. 

```
margin-left
margin-right
margin-top
margin-bottom
padding-left
padding-right
padding-top
padding-bottom
```

# 정렬
가로로 상중하, 세로로 상중하를 하여 6개의 셀을 기준으로 정렬하는 시스템이 필요할 듯 합니다. 이를 위한 클래스를 따로 설정하면 좋을 것 같습니다. 

# 폰트 크기
현재 폰트 사이즈는 중구 난방으로 정의되어있으며 코드를 쉽게 고치기 힘든 상태입니다. 유지 보수를 하려면 폰트 사이즈를 정규화하여 범위 내에서만 사용해야 할 것으로 보여집니다.

```
font-size
```

예를 들면 font-size의 약자 fs 그리고 style의 약자를 이용하여, fs-s1, fs-s2, fs-s3 등을 정의해야 할 것 같습니다.

```css
.font-size-xs1 {
    font-size: 1.6em;
}

.font-size-s2 {
    font-size: 0.9375em;
}

.font-size-s3 {
    font-size: 0.8125em;
}

.font-size-s4 {
    font-size: 0.875rem;
}

.font-size-s5 {
    font-size: 0.75em;
}

.font-size-s6 {
    font-size: 0.6875em;
}

```

예를 들면 위와 같습니다.

# 색상
공통된 색상을 미리 정의하고 그 색상만 써야 할 것 같습니다.

```
color
background-color
```

이때 CSS 내부에서 사용되는 CSS 변수 방법이 있고, HTML 파일 내 class로 추가하는 방법이 있습니다.

```css
:root {
   --red-color: red;
}

.red {
  color: red;
}
```

만들면서 느낀 것이지만 래퍼런스 사이즈에서 사용하는 색상, 크기는 몇 가지 되지 않았습니다.

이에 대한 정의를 common.css에 정의하면 좋을 것입니다.

- 중복된 CSS 속성 제거
- 변경 사항으로 인해 파일이 작동되지 않을 수 있으므로 단위 테스트 필수

여러 CSS 프레임워크의 존재를 보면 알겠지만, 

자세히 추상화를 하는 건 상당히 어려운 작업이라 장기적인 목표로 잡은 것입니다.

# 참고 자료
https://stackoverflow.com/a/10786695
https://css-tricks.com/starting-a-refactor-with-css-dig/
https://github.com/h5bp/html5-boilerplate
